name: run tests

on:
  push:
  pull_request:
  merge_group:

jobs:
  testGo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Golang caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Run go tests for client module
      working-directory: client
      run: |
        go test -v -cover -covermode=count ./...

    - name: Run go tests for publisher module
      working-directory: publisher
      run: |
        go test -v -cover -covermode=count ./...